# Listar todas as tarefas
GET http://localhost:8080/tasks
###

# Listar uma tarefa específica
GET http://localhost:8080/tasks/be77f0b6-f862-447e-bbd1-c9645cd94249
###

# Criar uma nova tarefa
POST http://localhost:8080/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Task 1",
  "description": "Description 1"
}
###

# Atualizar uma tarefa
PATCH http://localhost:8080/tasks/be77f0b6-f862-447e-bbd1-c9645cd94249 HTTP/1.1
Content-Type: application/json

{
  "description": "Updated Description 1"
}
###

# Completar uma tarefa
PATCH http://localhost:8080/tasks/be77f0b6-f862-447e-bbd1-c9645cd94249/complete HTTP/1.1
###

# Iniciar uma tarefa
PATCH http://localhost:8080/tasks/be77f0b6-f862-447e-bbd1-c9645cd94249/start HTTP/1.1
###

# Resetar o estado de uma tarefa (torna-la pendente)
PATCH http://localhost:8080/tasks/be77f0b6-f862-447e-bbd1-c9645cd94249/reset HTTP/1.1
###

# Deletar uma tarefa
DELETE http://localhost:8080/tasks/be77f0b6-f862-447e-bbd1-c9645cd94249

